spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    dbcp2:
      default-schema: public
  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

app:
  max-withdraw-in-one-time: ${MAX_WITHDRAW_IN_ONE_TIME}

springdoc:
  swagger-ui:
    path: /doc

#logging:
#  level:
#    sql: debug
#    web: debug
#    root: debug